name: Check Community Health Files
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Required Files
        run: |
          files=("README.md" "CONTRIBUTING.md" "CODE_OF_CONDUCT.md" "LICENSE" "SECURITY.md")
          for file in "${files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ $file is missing. Repository does not comply."
              exit 1
            fi
          done
          echo "✅ All required files are present."
